<?php
  include("header.php");
  include("navigation.php");
  include("inc/home/_hero.php");
  include("inc/home/_home-services.php");
  include("inc/home/_home-stories.php");
  include("inc/home/_home-articles.php");
  include("inc/home/_home-contact.php");
  include("footer.php");
?>